[workspace]
authors = ["parcels-benchmarks contributors"]
channels = ["conda-forge", "https://repo.prefix.dev/parcels"]
name = "parcels-benchmarks"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

lint = "pre-commit run --all-files"

[dependencies]

python = "3.12.*"
asv = ">=0.6.5"
pooch = ">=1.8.2"
pre_commit = "*"
py-rattler = "0.15.*"

[pypi-dependencies]
utils = { path = ".", editable = true}
